# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondecomer', '0002_auto_20160929_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOndecomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images-capa', verbose_name='Imagem')),
                ('decription', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Imagem_Ondecomer',
            },
        ),
    ]
