# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='palavralink',
            field=models.CharField(blank=True, max_length=120, verbose_name='palavra-link'),
        ),
    ]
