# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondeficar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ondeficar',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images-ondeficar', verbose_name='Imagem_1'),
        ),
        migrations.AlterField(
            model_name='ondeficar',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images-ondeficar', verbose_name='Imagem_2'),
        ),
        migrations.AlterField(
            model_name='ondeficar',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images-ondeficar', verbose_name='Imagem_3'),
        ),
        migrations.AlterField(
            model_name='ondeficar',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='images-ondeficar', verbose_name='Imagem_4'),
        ),
    ]
