# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondeficar', '0003_imageondeficar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ondeficar',
            name='contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
