# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondeficar', '0004_auto_20161005_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='ondeficar',
            name='link',
            field=models.CharField(blank=True, max_length=120, verbose_name='link'),
        ),
    ]
