# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artesanatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artesanato',
            name='contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contato'),
        ),
    ]
