# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praias', '0003_auto_20161005_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praia',
            name='address',
        ),
        migrations.RemoveField(
            model_name='praia',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='praia',
            name='description',
        ),
        migrations.RemoveField(
            model_name='praia',
            name='email',
        ),
        migrations.RemoveField(
            model_name='praia',
            name='site',
        ),
    ]
