# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praias', '0004_auto_20161006_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='praia',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
