# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praias', '0005_praia_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='praia',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='praia',
            name='contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='praia',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='praia',
            name='site',
            field=models.CharField(blank=True, max_length=100, verbose_name='Site'),
        ),
    ]
