# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images-servicos', verbose_name='Imagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name_plural': 'Categoria_Servicos',
                'ordering': ['name'],
                'verbose_name': 'Categoria_Servico',
            },
        ),
        migrations.CreateModel(
            name='ImageServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images-capa', verbose_name='Imagem')),
                ('decription', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Imagem_Servico',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Identificador')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Endereço')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='E-mail')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Contato')),
                ('site', models.CharField(blank=True, max_length=100, verbose_name='Site')),
                ('link', models.CharField(blank=True, max_length=120, verbose_name='link')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.CategoryServico', verbose_name='Categoria_Servicos')),
            ],
            options={
                'verbose_name_plural': 'Servicos',
                'ordering': ['name'],
                'verbose_name': 'Servico',
            },
        ),
    ]
