# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_auto_20161005_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='decription_1',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='decription_2',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='decription_3',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='decription_4',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='image_4',
        ),
        migrations.AddField(
            model_name='categoryservico',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images-servicos', verbose_name='Imagem'),
        ),
    ]
